### ISSUE TITLE
How do I configure my custom domain?

### ISSUE THREAD

**Issue by Turtle84375** [Turtle84375/turtle84375.github.io#1]
turtle84375.github.io is blocked on my computer, and I can't seem to connect www.turtle84375.com to it instead, even though the CNAME file get created and the setting is saved. It gives me a DSN record error... please help.

**Comment by FunctionalMetatable** [comment]
you need to own turtle84375.com, which is a paid domain. if you own said domain, you can configure the DNS records to point to `turtle84375.github.io`. You could try using replit for this instead. Hope this helps!

**Comment by Turtle84375** [comment]
Ah, thank you very much. I'll check it out.
